import {
    vidimg1,
    vidimg12,
    vidimg2,
    vidimg22,
    vidimg3,
    vidimg32,
    vidimg4,
    vidimg42,
    vidimg5,
    vidimg52,
    vidimg6,
    vidimg62,
    vidimg7,
    vidimg72,
    vidimg8,
    vidimg82,
    vidimg9,
    vidimg92,
    vidimg10,
    vidimg102,
    wz2logo,
    twitch_icon,
    instagram_icon,
    youtube_icon,
    twitter_icon,
    item1,
    item2,
    item3,
} from "../assets";

export const navLinks = [{
        id: "armes",
        title: "ARMES",
        path: "",
        submenu: [{
                id: "classesmw2",
                title: "CLASSES MWII",
                path: "/classes-mw2",
            },
            {
                id: "classesvanguard",
                title: "CLASSES VANGUARD",
                path: "/classes-vanguard",
            },
            {
                id: "classesmwcw",
                title: "CLASSES MW / CW",
                path: "/classes-mw-cw",
            },
        ],
    },
    {
        id: "evenements",
        title: "ÉVÈNEMENTS",
        path: "/evenements",
        submenu: [],
    },
    {
        id: "config",
        title: "CONFIG",
        path: "",
        submenu: [{
                id: "pcgaming",
                title: "PC GAMING",
                path: "/pc-gaming",
            },
            {
                id: "pcstreaming",
                title: "PC STREAMING",
                path: "/pc-streaming",
            },
            {
                id: "peripheriques",
                title: "PÉRIPHÉRIQUES",
                path: "/peripheriques",
            }
        ],
    },
    {
        id: "settings",
        title: "SETTINGS",
        path: "",
        submenu: [{
                id: "bindings",
                title: "BINDINGS",
                path: "/bindings",
            },
            {
                id: "settingswarzone",
                title: "SETTINGS WARZONE",
                path: "/settings-warzone",
            },
            {
                id: "settingsmw2",
                title: "SETTINGS MWII",
                path: "/settings-mw2",
            }
        ],
    },
    {
        id: "tatta",
        title: "LES BONS PLANS DE TATTA",
        path: "/promos",
        submenu: [],
    },
    {
        id: "configpcgaming",
        title: "CONFIG PC GAMING",
        path: "",
        submenu: [{
                id: "config1100",
                title: "CONFIG À 1100€",
                path: "/config-1100",
            },
            {
                id: "config1600",
                title: "CONFIG À 1600€",
                path: "/config-1600",
            },
            {
                id: "config1800",
                title: "CONFIG À 1800€",
                path: "/config-1800",
            }
        ],
    },
];
const vidInfos = [{
        id: "fifakill",
        name: "1VS1 contre FIFAKILL (double POV, on termine à 73 KILLS)",
        description: "Une vidéo en double POV, celle de @FifakillVizualz ainsi que la mienne. Une partie sur Ashika Island où on termine à 73 kills à deux, le gagnant est celui qui terminera avec le plus de kill.",
        duration: "13:26",
        date: "13 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=CNuJ7jkTMIM",
        thumbnail1: vidimg1,
        thumbnail2: vidimg12,
    },
    {
        id: "horrible",
        name: "Cette PARTIE est juste HORRIBLE 🤬",
        description: "Gameplay sur Ashika Island avec 3 français, une partie qui est juste horrible ! Une équipe me tombe en boucle, mon équipe meurt toutes les 5 minutes, bref c'était horrible, mais on a bien rigolé).",
        duration: "7:48",
        date: "11 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=GNsw8vnkyO4",
        thumbnail1: vidimg2,
        thumbnail2: vidimg22,
    },
    {
        id: "famille",
        name: "Toute sa FAMILLE me REGARDE ! (Il est fou de joie)",
        description: "En duo random avec un jeune abonné, il est tellement heureux de jouer avec moi, ça fait plaisir ! Il me raconte même que toute sa famille me regarde, son petit frère et même son beau père ",
        duration: "11:31",
        date: "10 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=wnXjJ8n0b0M",
        thumbnail1: vidimg3,
        thumbnail2: vidimg32,
    },
    {
        id: "snipompe",
        name: "J'UTILISE ce SNIPER comme un FUSIL A POMPE 🧠",
        description: "Un gameplay sur Al Mazraah avec un SA-B 50 à la mire. J'utilise ce sniper comme un fusil à pompe, j'ai pas peur de push mes adversaires grâce à cette classe. SA-B 50 MIRE : https://www.lordchow.fr/classes-mw2?p...",
        duration: "11:04",
        date: "9 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=HyBz4wS9kn0",
        thumbnail1: vidimg4,
        thumbnail2: vidimg42,
    },
    {
        id: "famillenombreuse",
        name: "Je DÉBARQUE dans une FAMILLE NOMBREUSE 👪",
        description: "Une partie sur Ashika Island en duo, où je me retrouve avec un jeune joueur, qui possède une famille nombreuse, et ça s'entend 🤣",
        duration: "10:33",
        date: "8 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=iX47hrNrwt4",
        thumbnail1: vidimg5,
        thumbnail2: vidimg52,
    },
    {
        id: "racaille",
        name: "Il fait la RACAILLE mais TERMINE avec 0 kill 🤣",
        description: "Je tombe sur un jeune joueur, qui parle comme une racaille, agit comme une racaille mais termine la partie avec 0 kill.",
        duration: "9:24",
        date: "7 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=4zKArWZLumA",
        thumbnail1: vidimg6,
        thumbnail2: vidimg62,
    },
    {
        id: "thefinals",
        name: "Ce nouveau FPS esport me fera-t-il arrêter Warzone ? 🚩",
        description: "The Finals est un jeu free-to-play avec des environnements destructibles et une approche réaliste qui pousse les limites de la compétitivité à un tout autre niveau. Les joueurs seront plongés dans des environnements immersifs et dynamiques, où chaque décision aura un impact sur le terrain de jeu.",
        duration: "12:24",
        date: "6 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=Cmoka32XWAE",
        thumbnail1: vidimg7,
        thumbnail2: vidimg72,
    },
    {
        id: "allo",
        name: "Allo Activision 📞 c'est quoi cette M*RDE ? 💩",
        description: "Lors de la sortie de Ashika Island, Activision a ajouté l'arbalète dans Warzone. Contrairement à Warzone premier du nom, cette 'nouvelle' arbalète est complétement nul. Pourquoi vous avez fait ça Activision ?",
        duration: "16:32",
        date: "5 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=7wBV0ToS644",
        thumbnail1: vidimg8,
        thumbnail2: vidimg82,
    },
    {
        id: "fou",
        name: "L'ARME qui rend FOUS tous les joueurs Warzone",
        description: "L'arme qui rend fou toute la communauté de Warzone depuis quelques jours : le KV BROADSIDE. Ce fusil à pompe est tout simplement MONSTRUEUX, voilà la classe que j'utilise : https://www.lordchow.fr/classes-mw2?p...",
        duration: "12:00",
        date: "4 mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=ydukrylHpuc",
        thumbnail1: vidimg9,
        thumbnail2: vidimg92,
    },
    {
        id: "host",
        name: "Je COMMENTE la COUPE DU MONDE de R6 (Six Invitational 2023)",
        description: "En ce moment, Rainbow Six Siege est à prix réduit ! Pour craquer : https://ubi.li/tiAYa",
        duration: "10:24",
        date: "3 Mars 2023",
        channel: "CHOWH1",
        link: "https://www.youtube.com/watch?v=bt16dS6LL-c",
        thumbnail1: vidimg10,
        thumbnail2: vidimg102,
    },
];
const agenda = [{
        id: "lundi",
        matin: {
            date: "March 13, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 13, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "mardi",
        matin: {
            date: "March 14, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 14, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "mercredi",
        matin: {
            date: "March 15, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 15, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "jeudi",
        matin: {
            date: "March 16, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 16, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "vendredi",
        matin: {
            date: "March 17, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 17, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "samedi",
        matin: {
            date: "March 18, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 18, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
    {
        id: "dimanche",
        matin: {
            date: "March 19, 2023 10:00:00 GMT+0100",
            img: wz2logo,
        },
        soir: {
            date: "March 19, 2023 20:00:00 GMT+0100",
            img: wz2logo,
        },
    },
]

const attirails = [".50 GS", "ARBALETE", "BAS-P", "BASILIC", "BRYSON 800", "BRYSON 890", "CHIMERA", "EBR 14"];

const social_links = [{
        id: "twitch",
        name: "CHOWH1",
        link: "https://www.twitch.tv/chowh1",
        logo: twitch_icon,
    },
    {
        id: "youtube",
        name: "CHOWH1",
        link: "https://www.youtube.com/channel/UCOM3hIIJ3ZcpWQEKProj5Ig",
        logo: youtube_icon,
    },
    {
        id: "youtube2",
        name: "CHOWH1 TV",
        link: "https://www.youtube.com/channel/UC2MkGUdvE1XERzDfsUdIZzg",
        logo: youtube_icon,
    },
    {
        id: "instagram",
        name: "CHOWH1",
        link: "https://www.instagram.com/chowh1/",
        logo: instagram_icon,
    },
    {
        id: "twitter",
        name: "CHOWH1_",
        link: "https://twitter.com/CHOWH1_",
        logo: twitter_icon,
    },
]

const items = [{
        id: "lorem1",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item1,
    },
    {
        id: "lorem2",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item2,
    },
    {
        id: "lorem3",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item3,
    },
    {
        id: "lorem4",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item1,
    },
    {
        id: "lorem5",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item2,
    },
    {
        id: "lorem6",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item3,
    },
    {
        id: "lorem7",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item1,
    },
    {
        id: "lorem8",
        name: "Lorem Ipsum",
        price: "100€",
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis eu iaculis urna. Aenean sit amet purus lacinia, pretium diam non, semper mi. Vestibulum nibh magna, lacinia a mauris quis, dictum ultrices velit. Quisque posuere id ante sit amet fringilla.",
        link: "",
        img: item2,
    },
]

export { vidInfos, agenda, attirails, social_links, items };